### ISSUE TITLE
Breaking change for fill value in area.lonlat2colrow

### ISSUE THREAD

**Issue by BENR0** [pytroll/pyresample#350]
#### Problem description
Before #340 `lonlat2colrow` (now `get_array_indices_from_lonlat`) the `fill_value` for the resulting masked arrays was set to -1. Now it is the numpy default (999999). Is this changed intended?

**Comment by djhoese** [comment]
I'm assigning this to @mraspaud as he made the changes. It looks intentional in the sense that the `fill_value=-1` is definitely no longer in the masking code. I'm curious though, how are you using this that it is causing issues? What are the downsides to one fill value over the other? Can you use `.filled()` to get the same result? Or are there performance issues?

**Comment by BENR0** [comment]
I just noticed and was investigating what changes were made. My code used `.filled()` but without `fill_value` argument and then later depended on `fill_value=-1`. I will be adapting my code. So from my side this can be closed.

**Comment by mraspaud** [comment]
Ok, so the lines that would need to be changed back are here: https://github.com/pytroll/pyresample/pull/340/files#diff-631d3c6d4c7d7db5cc47476746ef995875b87005f48dd42f2d2949547de8b598R1049-R1050
that is, re-add `fill_value=-1` there.
My thought was that instead of having just -1, we could have the actual value of the computed col row if relevant here below the mask.

But yeah, this is a breaking change. @BENR0 how problematic is it for you?

**Comment by mraspaud** [comment]
ok, saw your answer now.
I will just make a note in the documentation.
