### ISSUE TITLE
Assigning to slices/views of MaskedArray generates a warning

### ISSUE THREAD

**Issue by karldw** [pytroll/pyresample#66]
The KD tree code [manipulates the mask](https://github.com/pytroll/pyresample/blob/281549ccf9d82fa23d9b57a63283d186a43d29b2/pyresample/kd_tree.py#L720), which raises a [numpy warning](https://github.com/numpy/numpy/blob/master/doc/release/1.11.0-notes.rst#futurewarnings).

To replicate:
```python
from satpy.scene import Scene
global_scene = Scene(platform_name = "SNPP", sensor = "viirs", 
    base_dir = "viirs_test_download_2017-08-25_ND")
global_scene.load(["M10"])
global_scene.resample("worldeqc3km70")
```

I'm using numpy 1.13.1, satpy 0.7.1 and pyresample 1.5.0.

**Comment by davidh-ssec** [comment]
Thanks for pointing this out. I'll try to fix this next week if @mraspaud, others, and I can come to an agreement.

@mraspaud How about we force a copy of the input array? The `else` branch of that if statement (so if neighbors >= 1 or method is not nearest neighbor) doesn't have this issue from what I can tell because it is making a copy via arithmetic operations.

We could also have an optional `out` to do in-place writes, defaults to copy the input array.
